#pragma once

// ============================================
// PIPE SPRITE per MarioClockEffect
// Tubo verde classico Super Mario Bros
// Dimensioni: 16x18
// Lip largo 16px, corpo più stretto (12px) centrato
// ============================================

// Colori tubo
#define PIPE_GREEN_LIGHT 0x07E0   // Verde chiaro (highlight)
#define PIPE_GREEN       0x0560   // Verde medio (corpo)
#define PIPE_GREEN_DARK  0x0320   // Verde scuro (ombra)
#define PIPE_BLACK       0x0000   // Bordo nero
// Usa _MASK da assets.h per trasparenza (0x000E = SKY_COLOR)

// Tubo 16x18 pixel
const unsigned short PIPE_SPRITE[288] PROGMEM = {
    // Riga 0: top lip (16px largo)
    PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK,
    // Riga 1: lip
    PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK,
    // Riga 2: lip
    PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_BLACK,
    // Riga 3: base lip
    PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK,
    // Riga 4-17: corpo (14 righe) - 12px centrato con 2px trasparenti ai lati
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_GREEN_LIGHT, PIPE_GREEN_LIGHT, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN, PIPE_GREEN_DARK, PIPE_GREEN_DARK, PIPE_BLACK, _MASK, _MASK,
    _MASK, _MASK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, PIPE_BLACK, _MASK, _MASK,
};

const byte PIPE_SPRITE_SIZE[2] = {16, 18};